# Generated by Django 4.2.17 on 2025-01-06 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kpis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('interval', models.IntegerField(help_text='Interval in seconds')),
                ('kpi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpis.kpi')),
            ],
        ),
    ]
