# Generated by Django 4.2.17 on 2025-01-07 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_kpiresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KPIResult',
        ),
    ]
